.PHONY: all
all:
	curl http://dl.google.com/closure-compiler/compiler-latest.zip > compiler-latest.zip
	unzip compiler-latest.zip
	rm -f compiler-latest.zip

.PHONY: clean
clean:
	rm -f compiler-latest.zip compiler.jar README COPYING
